lib/traject/psulib_config.rb

Connected to #37 
**Additional Changes:** moved serial title mapping upper and removed comments out and added to Titles wiki  - no changes to logic

Mapping serials preceding and succeeding entry fields - #37

---

config/schedule.rb
lib/tasks/incrementals.rake

* Adds ability to specify hourly or daily
Just allowed the passing of an arg for period and modified the tasks to account for that. This is assuming things about where the data is put. This is subject to change when the production indexer server is ready

* Adds ability to specify qa or prod

---

.travis.yml
Gemfile
Gemfile.lock
README.md
spec/spec_helper.rb

additionally I removed a gem called `ruby-debug` because it kept giving this error below and I didn't think we used it anyway:
```
➜  psulib_traject git:(codeclimate) ✗ bundle exec rake
jruby: warning: unknown property jruby.cext.enabled
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jruby.util.SecurityHelper to field java.lang.reflect.Field.modifiers
WARNING: Please consider reporting this to the maintainers of org.jruby.util.SecurityHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
sBundler could not find compatible versions for gem "linecache":
In snapshot (Gemfile.lock):
linecache (= 1.3.1)
In …
```

Replaces coveralls with code climate

---

.rubocop.yml
.rubocop_todo.yml

see 
```
.rubocop_todo.yml: Metrics/LineLength has the wrong namespace - should be Layout
The following cops were added to RuboCop, but are not configured. Please set Enabled to either `true` or `false` in your `.rubocop.yml` file:
- Layout/EmptyLinesAroundAttributeAccessor (0.83)
- Layout/SpaceAroundMethodCallOperator (0.82)
- Lint/DeprecatedOpenSSLConstant (0.84)
- Lint/RaiseException (0.81)
- Lint/StructNewOverride (0.81)
- Style/ExponentialNotation (0.82)
- Style/HashEachMethods (0.80)
- Style/HashTransformKeys (0.80)
- Style/HashTransformValues (0.80)
- Style/SlicingWithRange (0.83)
For more information: https://docs.rubocop.org/en/latest/versioning/
```

Allows all new cops to be enabled and fixes namespace change in todo

---

config/settings.yml
lib/tasks/incrementals.rake

* Also adds a new config gem setting to replace the random symphony path constant
#203 
The idea will be that we can create a monitor that expects these parsed messages to occur at various times a day, or by total count in a day, or something like that. There are different options I think, but, bottom line is it gets us a view on our incrementals that Splunk can alert us about without us having to try and wire up some directory watching service or emailing directly from code, etc.
Might be a good idea to do a test deploy and see if it does to the logs what I'm hoping it does. Locally it did this:
```
2020-09-30T22:15:35-04:00  INFO name=Sirsi Incremental message=Indexing operation beginning task=hourly import progress=start
2020-09-30T22:15:35-04:00  INFO jruby 9.2.11.1 (2.5.7) 2020-03-25 …
```

Makes logs easier to parse and monitor with Splunk

---

lib/tasks/docker.rake
lib/tasks/solr.rake

Changes the Docker rake tasks to use "psul_catalog" as the collection name, which matches the name in settings.yml. The solr tasks file is renamed to "solr" to lineup with the namespace.

Update Docker and Solr related tasks

---

Gemfile

We can run either MRI or JRuby locally depending on our needs.
Switching back and forth between jruby and MRI will change the lock file, but this way, you can just not commit and changes and flip back more easily.

Load jruby debugger accordingly

---

README.md
lib/tasks/docker.rake
spec/lib/psulib_traject/solr_manager_spec.rb

This allows us to run Solr on a different port, which is helpful if you have multiple apps running with their own Solr, or want to test different versions on different ports.
This will likely all go away when we have a proper Docker compose setup, but this is mostly for me so I can run Scholarsphere and the catalog simultaneously.

Configure Solr's port

---

Gemfile.lock

I'm not sure what went sideways here, but syncing it up

updates lockfile for versions of jruby we're using in docker

---

config/traject.rb
lib/psulib_traject/call_number.rb
spec/lib/psulib_traject/call_number_spec.rb

The keymap_struct needs to indicate which key is the forward and reverse key. This will allow to us build the correct list when retrieving them from Solr in the catalog.
Related to #285

Return explicit shelf key types in struct

---

.circleci/config.yml
.rspec
spec/lib/psulib_traject/workers/hourly_indexer_spec.rb
spec/support/sidekiq.rb

This makes two small changes:
1. Add rubocop to the CI build (also corrects outstanding linting errors)
2. Use `--format documentation` for RSpec because it creates a more readable output

Rubocop and RSpec

---

.rubocop.yml
lib/psulib_traject.rb
lib/psulib_traject/null_object.rb
lib/psulib_traject/shelf_key.rb
spec/lib/psulib_traject/null_object_spec.rb
spec/lib/psulib_traject/shelf_key_spec.rb

If we can't determine a proper shelf key, we need to return nil. Otherwise, querying on shelf keys that have bad characters in them will cause errors in Solr
I've tested this with our catalog's call number branch, and this doesn't seem to break anything, and it should fix the errors we're seeing with Solr queries. All of the LC numbers that have bad characters in them, ex (?:, are all in call numbers that Lcsort can't process. Returning nothing is the better option here. Later, we can attempt to try our own process for this call numbers.
Related to #285

NullKey for unparseable LC call numbers

---

lib/psulib_traject/workers/hourly_indexer.rb

hourlies_directory.children wasn't returning all the files recursively. Dir.glob, with the appropriate glob pattern does. Since Dir.glob returns an array of strings, I no longer need to call .to_s either.

Pathname.children is not recusrive

---

lib/psulib_traject/call_number.rb
spec/lib/psulib_traject/call_number_spec.rb
spec/lib/psulib_traject/holdings_spec.rb

Records with local and periodical call numbers were being incorrectly identified as LC numbers.

Update local and periodical exclusion rules

---

lib/psulib_traject/shelf_key.rb
spec/lib/psulib_traject/shelf_key_spec.rb

When Lcsort is not able to create a shelf key, we manipulate the call number into something that it can sort. Lower case characters are converted to numbers, colons are removed, and a zero is added to the LC classification if no number is present.
If a call number has lower-case values in the cutter, ex. `PZ7.H56774Fou 2014` the key will look like `PZ.0007.H56774.F1420--2014` where the "ou" has been translated into "1420". This way, the key should still sort. Cases like `LD4481.P8kG45` produce a key that looks like `LD.4481.P810.G45--2008`, where the "k" is replaced with "10".
If the LC classification part of the call number has no digits, ex. `KKP.B634b`, we add a zero. This assumes that "KKP" would sort _before_ "KKP1" or "KKQ". So the preceding example has a key that looks like …

Custom shelf keys for LC call numbers

---

.rubocop.yml
config/traject.rb
lib/psulib_traject.rb
lib/psulib_traject/macros.rb
lib/psulib_traject/macros/subjects.rb
spec/lib/psulib_traject/macros/subjects_spec.rb
spec/records/subjects.rb

Addresses #329 
Creates a new `subject_browse_facet` field to support browsing subjects. Includes a refactoring of our existing macros, which splits out the subject-related macros into their own file, then refactors the tests and macro code separately.

Add subject_browse_facet

---

lib/psulib_traject/macros/subjects.rb
spec/lib/psulib_traject/macros/subjects_spec.rb
spec/records/subjects.rb

mapping was failing for records with weird 650s
eg. https://catalog.libraries.psu.edu/catalog/14651589/marc_view

fix for subjects when record with 650 has an indicator but no subfields

---

spec/integration/access_facet_spec.rb
spec/integration/config_spec.rb
spec/lib/psulib_traject/marc_combining_reader_spec.rb
spec/lib/psulib_traject/processors/pub_date_spec.rb
spec/spec_helper.rb
spec/support/helpers.rb

Extracts out our helpers into their own file to keep the spec_helper file a little leaner.
Note: this was some refactoring that was part of another PR that we ended up not needing, so I'm just putting it here so we don't waste it.

Clean up spec_helper

---

lib/psulib_traject/periodical_holdings.rb
spec/lib/psulib_traject/periodical_holdings_spec.rb
spec/records/summary_holdings.rb

866, 867, and 868 fields have summary holdings information in subfields other than just |a, so we need to index all these subfields.
Fixes #373

Use any a-z subfield for summary holdings information

---

config/traject.rb

Re: #57.
We extract the endowment fund name and code into a single Solr field for keyword search, but we only want to display fund name in the UI.

Extract the endowment fund name so it can be used for display

---

Gemfile.lock
config/traject.rb

There were periods at the end of the subjects and I don't think we want them displaying that way in the Cat.  I found this 'trim_punctuation' parameter that seems to fix it.  I'm not sure where 'trim_punctuation' is defined though.

Adds trim_punctuation to subject_other_display field

---

config/traject.rb

`series_title_strict_tsim` strictly contains just the title of the series (490a or 440a).  No extra stuff.
Linked: https://github.com/psu-libraries/psulib_blacklight/pull/982

Adds series_title_strict_tsim to traject

---

lib/psulib_traject/macros.rb

The thought is that not allocating an array each time will reduce the performance bottleneck that indexing thesis codes introduced.

Use a frozen regex to compare PSU thesis codes to speed up indexing

---

config/traject.rb
lib/psulib_traject.rb
lib/psulib_traject/macros.rb
lib/psulib_traject/processors/oclc_extract.rb
spec/lib/psulib_traject/macros_spec.rb
spec/lib/psulib_traject/processors/oclc_extract_spec.rb

Some of this code could potentially be refactored and abstracted into its own Processor class.  I didn't do this though since there were some shared methods in the Macros module.  I felt this needed a test too. The one I added seems a bit weird and there may be a better way of doing it, but it works.
closes #404

Extract deprecated oclcs

---

lib/psulib_traject/macros.rb
spec/integration/macros_spec.rb

Closes https://github.com/psu-libraries/psulib_blacklight/issues/428
- allow any combination of upper/lowercase for `http(s)://` prefix
- prepend `http://` to URLs that start with `www.`

Fix issues with some 856 URLs not being indexed for display

---

lib/psulib_traject/workers/hourly_indexer.rb

On some systems, Dir.glob does not return a sorted list, this could cause us to process incrementals out of order when we replay them. 
Calls .sort on Dir.glob calls to return a sorted list.

sort Dir.glob

---

lib/psulib_traject/call_number.rb
lib/psulib_traject/processors/call_number/base.rb
spec/lib/psulib_traject/processors/call_number/lc_spec.rb

I wonder if we could get the trimming to run the `#remove_by_regex` method in a loop until it no longer finds any more regex matches?  It looks like it's just trimming once, so if it matches to something at the end of the call number and misses something closer to the front of the call number, it doesn't do all the trimming it should.
closes #393

Modified regex for trimming call numbers to handle more permutations

---

config/traject.rb
lib/psulib_traject/macros.rb
spec/integration/macros_spec.rb

Also, adds more subfields to be parsed for the genre facet.  The same subfields the main genre field uses.
closes #185

Parse more genres and separate multiple internal genres

---

config/traject.rb
spec/integration/config_spec.rb

Stripping leading and trailing whitespace from 653a's and splitting 653a into separate items on ';'s.
closes #416

Split 653a on semicolon

---

config/traject.rb

Removes all subfields from serials marc extraction except 't' (title).
closes #421

Removed all subfields except t subfields in serials traject fields

---

Dockerfile
config/settings.yml
lib/psulib_traject/solr_manager.rb
lib/psulib_traject/workers/hourly_indexer.rb
lib/tasks/traject.rake
spec/lib/psulib_traject/workers/hourly_indexer_spec.rb

- figures out what the collection name is if using an alias
- uses that collection name as a key in redis to track hourlies
This allows us to process hourlies _before_ flipping the collection on a full re-index.

Track hourlies by collection, not alias 

---

lib/psulib_traject/holdings.rb
spec/lib/psulib_traject/holdings_spec.rb

Replaced `online?` method in `holdings.rb` with `not_in_the_library?` method that checks if the record's `access_facet` includes 'In the Library'.  If a record is not in the library it will not have a callnumber.  On the other hand, _anything_ (including records that are also online) that is in the library will have a callnumber.  Added some tests to test a couple different variations of `access_facets`.

Store callnumber if record is 'In the Library'

---

config/traject.rb
lib/psulib_traject/macros.rb
spec/integration/macros_spec.rb

Adds thesis_dept display field to traject extracts.  Removes 'THESIS-B' from thesis codes allowed to be indexed.
closes #305 
blacklight side: https://github.com/psu-libraries/psulib_blacklight/pull/1199

Thesis Department index

---

.gitignore
.rubocop.yml
Gemfile.lock
config/traject.rb
lib/psulib_traject.rb
lib/psulib_traject/processors/pub_display.rb
spec/integration/publication_spec.rb
spec/lib/psulib_traject/processors/pub_display_spec.rb

Fixes #176 
New processor moves period to the left side for vernacular publication fields in right to left languages

right to left language formatting

---

Gemfile
Gemfile.lock
spec/lib/psulib_traject/workers/hourly_indexer_spec.rb

Bumping sidekiq required sidekiq-scheduler to be upgraded as well.
The hourly indexer spec was failing. It seemed like it was only removing keys that had `hr` but none of them did, so it wasn't actually removing anything.

Sidekiq update

---

config/traject.rb
lib/psulib_traject/macros.rb
spec/integration/macros_spec.rb

closes #503 
If 857 starts with our ark prefix, adds it to the sublocation ssm.

503 - Grabs 857 field if it starts with ark

---

config/traject.rb
lib/psulib_traject/call_number.rb
spec/lib/psulib_traject/call_number_spec.rb

fixes #406 
Now indexing SUDOC values.  The next step of this would be to start identifying what kind of processing needs done on these.  We may want to set up a preview branch for this and have it do a full index.  Then output a large subset of these for Ruth to look at.

Index SUDOC values
