Gemfile, Gemfile.lock, README.md, Rakefile
1. changes namespace to solr from psulib_traject:solr
2. adds 3 tasks, up, clean and stop
3. updates documentation accordingly
=> #49 docker instead solr wrapper

Rakefile, psulib_config.rb
=> #52 schemaxml update

psulib_config.rb
Added one really important character. 
Related to https://github.com/psu-libraries/psulib_blacklight/issues/185
=> Replacing all_authors_facet_sim with all_authors_facet_ssim

psulib_config.rb
=> removing 700/710/711 from title-related fields

lib/traject/psulib_config.rb, spec/lib/traject/bound_with_spec.rb
this is tied to https://github.com/psu-libraries/psulib_blacklight/pull/200
=> Catalog link

lib/traject/psulib_config.rb
related to fixes in https://github.com/psu-libraries/psulib_blacklight/pull/211
=> Material characteristics cont

lib/traject/psulib_config.rb, lib/traject/psulib_marc.rb, spec/lib/traject/psulib_marc_spec.rb
=> mapping genres #22

lib/traject/psulib_config.rb
=> Updating marc language fields

lib/traject/psulib_config.rb, spec/lib/traject/audience_spec.rb
Connected to #80 
adds a spec for qualified audience along with basic code to handle this
=> #80 audience characteristics qualifier

lib/traject/psulib_config.rb
=> #15 mapping notes

Gemfile.lock, lib/traject/psulib_config.rb
=> #101 identifiers

lib/traject/psulib_config.rb
=> Adding dates_of_pub_ssim

lib/traject/psulib_config.rb, spec/lib/traject/psulib_config_spec.rb
=> Logic and spec for conditional separators on Music Numerical field

lib/marc_media_type_processor.rb
=> removing for AVC check from material types #125

lib/traject/psulib_config.rb, spec/lib/traject/psulib_config_spec.rb
=> mapping call numbers #32

config/indexer_settings_prod.yml, config/schedule.rb, lib/tasks/incrementals.rake, lib/traject/psulib_config.rb
You'll see what got changed in the commit messages, basically: had to fix some typos, adding some environment variable juggling and loading of indexer settings because log files were wrong in the incremental processing. Also threw in the email output of whenever just for fun.
=> Incrementals fix

config/indexer_settings.yml, config/indexer_settings_production.yml, lib/traject/psulib_config.rb
Traject uses slightly different settings than BL for connecting to the collection
=> This would take care of indexing to prod

lib/traject/psulib_config.rb
Connected to psu-libraries/psulib_blacklight#288
=> removing author sort

lib/tasks/incrementals.rake
=> Simplifying. Relying on the addupdates being mrc files.

lib/traject/psulib_config.rb
Issue #167 and also additional work: Issue #199
=> mapping 799a sublocation field

lib/traject/psulib_config.rb
updating title to fix issue #190
=> adding subfield H to title latin and vernacular

Gemfile, Gemfile.lock
See https://github.com/codeclimate/test-reporter/issues/418
=> CodeClimate does not work with version 0.18 or greater of simplecov

README.md, config/indexer_settings_dev.yml, lib/tasks/docker.rake, lib/tasks/hathi_etas.rake
=> hathi etas tasks

.rubocop_todo.yml, lib/traject/macros/custom.rb, spec/lib/traject/macros/custom_spec.rb
=> need to strip oclc leading zeros for hathi data lookup

.rubocop_todo.yml, lib/traject/macros/custom.rb, spec/lib/traject/macros/custom_spec.rb
=> for hathi multi records with a mix of ETAS and PD, suppress allow

.gitignore, Gemfile, Gemfile.lock, config/indexer_settings_dev.yml, config/indexer_settings_production.yml, config/indexer_settings_qa.yml, config/indexer_settings_test.yml, config/settings.yml, config/settings/test.yml, lib/traject/psulib_config.rb
#232
Also will be required by changes to the deploy script in https://github.com/psu-libraries/psulib_blacklight_deploy/issues/80
=> Adds config gem to replace homegrown config management.

lib/tasks/hathi_trust.rake
there might be a better way to do this 🤔
=> had to add config setup to hathi rake task

lib/marc_format_processor.rb
To address https://github.com/psu-libraries/psulib_traject/issues/186#issuecomment-702250781
=> test for university in publisher to address govt pub vs book

lib/tasks/incrementals.rake
gah, hope this is the last one
=> Make sure program exits when no target is there

lib/tasks/hathi_trust.rake
=> task for hathi exclude list

lib/marc_access_facet_processor.rb, spec/lib/traject/access_facet_spec.rb
=> exclude UP-OFFICE from access facet

.github/workflows/ci.yml, Gemfile, config/schedule.rb
Uses Github's workflow to run a CI build.
=> Setting up CI build

lib/traject/macros/custom.rb, spec/lib/traject/macros/custom_spec.rb
=> adding prefix, label and notes to links

lib/marc_access_facet_processor.rb, spec/lib/traject/access_facet_spec.rb
=> Rename "Open Access" facet to "Free to Read"

spec/lib/traject/media_types_spec.rb
Refactors the media types spec test and increases coverage to 100%.
=> Update media types spec test

config/traject.rb
=> Index 993a and 993n for endowment info keyword search and display

config/traject.rb
=> index report numbers

config/traject.rb
Fixes #367 again. We missed a field on the first go-round.
=> Adds 086a to report numbers field

config/traject.rb
=> Index 995 fields for dedication info keyword search and display

lib/psulib_traject/macros.rb, spec/integration/macros_spec.rb
=> changing rules for full and partial links so to prevent colliding urls

config/traject.rb
=> Index more subfields of 995 for dedication info

lib/psulib_traject/macros.rb, spec/integration/macros_spec.rb
#382 
Note: not to be merged until rule is clarified by @ruthtillman: https://github.com/psu-libraries/psulib_traject/issues/382#issuecomment-1012344809
=> Fulltext links rule update

config/traject.rb, lib/psulib_traject/macros.rb, spec/integration/macros_spec.rb
=> Index 699a (Thesis Department) for faceting and advanced search

config/traject.rb
=> Adds extraction for binding info.

config/traject.rb, lib/psulib_traject/call_number.rb, lib/psulib_traject/shelf_key.rb, spec/lib/psulib_traject/call_number_spec.rb, spec/lib/psulib_traject/shelf_key_spec.rb
=> updates for call number browse field re stringdiff plugin

lib/translation_maps/locations.properties
Beaver added a new location for textbooks
=> new location for Beaver textbooks

lib/psulib_traject/macros.rb, spec/integration/macros_spec.rb
Project issue: https://github.com/psu-libraries/psulib_blacklight/issues/1007
=> Change label for finding aids directed to our special collections materials

config/traject.rb
closes #433 
blacklight: https://github.com/psu-libraries/psulib_blacklight/pull/1082
=> Adds 773 extract with trim_punctuation

lib/psulib_traject/macros.rb, spec/integration/macros_spec.rb
Reverts psu-libraries/psulib_traject#435
Reference https://github.com/psu-libraries/psulib_blacklight/issues/1007
Blacklight changes: https://github.com/psu-libraries/psulib_blacklight/pull/1084
=> Revert "Change label for finding aids directed to our special collections materials"

lib/translation_maps/locations.properties
a few updates came in this week
=> new locations and location updates

config/traject.rb
=> added facet field for author demographics

Dockerfile
jruby upgrade needs netbase added to the container
=> adds netbase

config/traject.rb
=> Combine biographical sketch and administrative history fields into one

.gitignore, Gemfile.lock, config/traject.rb, lib/psulib_traject/macros.rb, spec/integration/macros_spec.rb
=> Supress 700 and 710 fields if owner is found

.circleci/config.yml
Look into adding it back or adjusting later on.
=> Remove codeclimate for now. 
